name: CI
on:
  push:
    paths:
      - ".github/workflows/**"
      - "**.nim"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        branch: [devel]

    name: 'Nim ${{ matrix.branch }}'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: uniony

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          path: uniony

      - name: Setup Nim
        uses: alaviss/setup-nim@0.1.1
        with:
          path: nim
          version: ${{ matrix.branch }}

      - name: Install dependencies
        run: nimble install -y --depsOnly

      - name: Run tests
        run: nimble test
